# Generated by Django 5.1.4 on 2024-12-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='packages/')),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='package',
            name='extra_images',
            field=models.ManyToManyField(blank=True, to='travel.packageimage'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
