# Generated by Django 5.1.4 on 2024-12-18 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_packageimage_alter_package_extra_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageimage',
            name='description',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='packageimage',
            name='image',
            field=models.ImageField(upload_to='packages/extra_images/'),
        ),
    ]
