# Generated by Django 5.1.4 on 2025-01-01 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_alter_packageimage_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='packager_profiles/')),
                ('other_details', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='packager_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
