# Generated by Django 5.0.2 on 2025-01-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('short_description', models.TextField()),
                ('rating', models.FloatField(default=0.0)),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='hotels/')),
                ('map_url', models.URLField()),
                ('extra_images', models.ManyToManyField(blank=True, to='travel.image')),
            ],
        ),
    ]
