# Generated by Django 5.1.4 on 2025-02-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_booking_additional_info_booking_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='map_url',
            field=models.URLField(max_length=700),
        ),
    ]
