# Generated by Django 5.1.4 on 2025-02-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_alter_package_map_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='map_url',
            field=models.URLField(max_length=800),
        ),
    ]
