# Generated by Django 5.1.4 on 2025-02-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_alter_place_map_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
