# Generated by Django 5.1.4 on 2025-02-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0014_place_email_place_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='email',
        ),
        migrations.RemoveField(
            model_name='place',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='packagerprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='packagerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
