# Generated by Django 5.1.4 on 2025-02-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0015_remove_place_email_remove_place_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
