# Generated by Django 5.1.4 on 2025-02-01 13:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0016_package_email_package_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagerprofile',
            name='map_url',
            field=models.URLField(default=django.utils.timezone.now, max_length=700),
            preserve_default=False,
        ),
    ]
