# Generated by Django 5.1.4 on 2025-02-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0017_packagerprofile_map_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='map_url',
            field=models.URLField(max_length=800),
        ),
    ]
