# Generated by Django 5.1.4 on 2025-02-02 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0018_hotel_email_hotel_location_hotel_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='location',
        ),
    ]
