# Generated by Django 5.1.4 on 2025-02-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0019_remove_hotel_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
