# Generated by Django 5.1.4 on 2025-02-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0020_hotel_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='packager_documents/'),
        ),
    ]
