# Generated by Django 5.1.4 on 2025-02-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0025_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
