from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', views.home, name='home'),
    path('places/', views.all_places, name='all_places'), 
    path('places/<int:pk>/', views.place_detail, name='place_detail'),
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('profile/', views.user_profile, name='user_profile'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('packages/', views.all_packages, name='all_packages'),
    path('packages/<int:pk>/', views.package_detail, name='package_detail'),
    path('packager/dashboard/', views.packager_dashboard, name='packager_dashboard'),
    path('packager/add/', views.add_package, name='add_package'),
    path('packager/edit/<int:pk>/', views.edit_package, name='edit_package'),
    path('packager/delete/<int:pk>/', views.delete_package, name='delete_package'),
    path('packager/profile/create/', views.create_profile, name='create_profile'),
    path('packager/profile/edit/', views.edit_profile, name='edit_profile'),
    path('packager/profile/view/', views.view_profile, name='view_profile'),
    path('packager/<int:packager_id>/', views.packager_detail, name='packager_detail'),
    path('packagers/', views.all_packagers, name='all_packagers'),
    path('customer/profile/create/', views.create_customer_profile, name='create_customer_profile'),
    path('customer/profile/edit/', views.edit_customer_profile, name='edit_customer_profile'),
    path('write-review/', views.write_review, name='write_review'),
    path('reviews/', views.review_section, name='review_section'),
    path('all-reviews/', views.all_reviews, name='all_reviews'),
    path('hotels/', views.all_hotels, name='all_hotels'),
    path('hotels/<int:pk>/', views.hotel_detail, name='hotel_detail'),
    path('about-us/', views.about_us, name='about_us'),
    path('whatsnew/', views.whats_new, name='whats_new'),
    path('terms_use/', views.terms_use, name='terms_use'),
    path('technical_support/', views.technical_support, name='technical_support'),
    path('trust_security/', views.trust_security, name='trust_security'),
    path('faq/', views.faq, name='faq'),
    path('privacy_policy/', views.privacy_policy, name='privacy_policy'),
    path('gallery/', views.gallery, name='gallery'),
    path('upload_image/', views.upload_image, name='upload_image'),
    path('packages/book/<int:pk>/', views.book_package, name='book_package'),
    path('packager/bookings/accept/<int:booking_id>/', views.accept_booking, name='accept_booking'),
    path('packager/bookings/reject/<int:booking_id>/', views.reject_booking, name='reject_booking'), 
    path('ask_faq/', views.ask_faq, name='ask_faq'),
    path('view_faqs/', views.view_faqs, name='view_faqs'),   
    path('packagers/<int:packager_id>/chat/', views.start_chat, name='start_chat'),
    path('chat/<int:user_id>/', views.chat_view, name='chat_view'),
    path('my_chats/', views.my_chats, name='my_chats'),
    path('users_chats/', views.users_chats, name='users_chats'),
    path('change-password/', views.change_password, name='change_password'),
]

